
package jud.gestorfacturas.gui.view;

import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import jud.gestorfacturas.gui.controller.FacturaController;
import jud.gestorfacturas.model.Factura;

public class FacturaView extends javax.swing.JFrame {

    FacturaController controller;
    
    /**
     * Creates new form NewApplication
     */
    
    public FacturaView(FacturaController _controller) {
        this.controller = _controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel = new javax.swing.JPanel();
        facturaPanel = new javax.swing.JPanel();
        datosFacturaTitulolbl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datosFacturaCuerpoPanel = new javax.swing.JPanel();
        numeroFralbl = new javax.swing.JLabel();
        numeroFraTxtField = new javax.swing.JTextField();
        fechaEmisionlbl = new javax.swing.JLabel();
        fechaEmisionTxtField = new javax.swing.JTextField();
        diasParaPagolbl = new javax.swing.JLabel();
        diasParaPagoTxtField = new javax.swing.JTextField();
        fechaVencimientolbl = new javax.swing.JLabel();
        fechaVencimientoTxtField = new javax.swing.JTextField();
        formaPagolbl = new javax.swing.JLabel();
        formaPagoComboBox = new javax.swing.JComboBox<>();
        clientePanel = new javax.swing.JPanel();
        datosClientePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        clienteTitulolbl = new javax.swing.JLabel();
        nombreClienteSearchBtn = new javax.swing.JButton();
        numeroClienteTxtField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        nombreClientelbl = new javax.swing.JLabel();
        nombreClienteTxtField = new javax.swing.JTextField();
        nifClientelbl = new javax.swing.JLabel();
        nifClienteTxtField = new javax.swing.JTextField();
        direccionClientelbl = new javax.swing.JLabel();
        direccionClienteTxtField = new javax.swing.JTextField();
        codigoPostalClientelbl = new javax.swing.JLabel();
        codigoPostalClienteTxtField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        msgPanel = new javax.swing.JPanel();
        msgContainerPanel = new javax.swing.JPanel();
        msgLbl = new javax.swing.JLabel();
        facturacionPanel = new javax.swing.JPanel();
        facturacionTituloPanel = new javax.swing.JPanel();
        facturacionTitulolbl = new javax.swing.JLabel();
        conceptosPanel = new javax.swing.JPanel();
        conceptosTituloLabel = new javax.swing.JLabel();
        cantidadTituloLabel = new javax.swing.JLabel();
        precioTituloLabel = new javax.swing.JLabel();
        totalImporteTituloLabel = new javax.swing.JLabel();
        concepto1TxtField = new javax.swing.JTextField();
        cantidad1TxtField = new javax.swing.JTextField();
        precio1TxtField = new javax.swing.JTextField();
        totalImporte1TxtField = new javax.swing.JTextField();
        concepto2TxtField = new javax.swing.JTextField();
        cantidad2TxtField = new javax.swing.JTextField();
        precio2TxtField = new javax.swing.JTextField();
        totalImporte2TxtField = new javax.swing.JTextField();
        concepto3TxtField = new javax.swing.JTextField();
        cantidad3TxtField = new javax.swing.JTextField();
        precio3TxtField = new javax.swing.JTextField();
        totalImporte3TxtField = new javax.swing.JTextField();
        concepto4TxtField = new javax.swing.JTextField();
        cantidad4TxtField = new javax.swing.JTextField();
        precio4TxtField = new javax.swing.JTextField();
        totalImporte4TxtField = new javax.swing.JTextField();
        idiomaOrigenTituloLabel = new javax.swing.JLabel();
        idiomaOrigen1TxtField = new javax.swing.JTextField();
        idiomaOrigen2TxtField = new javax.swing.JTextField();
        idiomaOrigen3TxtField = new javax.swing.JTextField();
        idiomaOrigen4TxtField = new javax.swing.JTextField();
        idiomaDestinoTituloLabel = new javax.swing.JLabel();
        idiomaDestino1TxtField = new javax.swing.JTextField();
        idiomaDestino2TxtField = new javax.swing.JTextField();
        idiomaDestino3TxtField = new javax.swing.JTextField();
        idiomaDestino4TxtField = new javax.swing.JTextField();
        TipoTituloLabel = new javax.swing.JLabel();
        item1ComboBox = new javax.swing.JComboBox<>();
        item2ComboBox = new javax.swing.JComboBox<>();
        item3ComboBox = new javax.swing.JComboBox<>();
        item4ComboBox = new javax.swing.JComboBox<>();
        buttonsPanel = new javax.swing.JPanel();
        verificarFichaBtn = new javax.swing.JToggleButton();
        previewFacturaBtn = new javax.swing.JButton();
        registrarFacturaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestor de facturación");
        setMinimumSize(new java.awt.Dimension(900, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel.setLayout(new java.awt.GridBagLayout());

        facturaPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        facturaPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facturaPanel.setLayout(new java.awt.BorderLayout());

        datosFacturaTitulolbl.setFocusable(false);
        datosFacturaTitulolbl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("FACTURA");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        datosFacturaTitulolbl.add(jLabel1);

        facturaPanel.add(datosFacturaTitulolbl, java.awt.BorderLayout.NORTH);

        datosFacturaCuerpoPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        datosFacturaCuerpoPanel.setLayout(new java.awt.GridBagLayout());

        numeroFralbl.setText("Número de factura");
        numeroFralbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        datosFacturaCuerpoPanel.add(numeroFralbl, gridBagConstraints);
        numeroFralbl.getAccessibleContext().setAccessibleDescription("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(numeroFraTxtField, gridBagConstraints);

        fechaEmisionlbl.setText("Fecha de emisión");
        fechaEmisionlbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        datosFacturaCuerpoPanel.add(fechaEmisionlbl, gridBagConstraints);

        fechaEmisionTxtField.setToolTipText("Son válidos cualquiera de los siguientes formatos:\ndd/MM/yyyy\ndd-MM-yyyy\ndd/MM/yy\ndd-MM-yy\nddMMyyyy\nddMMyy");
        fechaEmisionTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechaEmisionTxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(fechaEmisionTxtField, gridBagConstraints);

        diasParaPagolbl.setText("Días para pago");
        diasParaPagolbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        datosFacturaCuerpoPanel.add(diasParaPagolbl, gridBagConstraints);

        diasParaPagoTxtField.setToolTipText("Ha de ser un número entero");
        diasParaPagoTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diasParaPagoTxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(diasParaPagoTxtField, gridBagConstraints);

        fechaVencimientolbl.setText("Fecha de vencimiento");
        fechaVencimientolbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        datosFacturaCuerpoPanel.add(fechaVencimientolbl, gridBagConstraints);

        fechaVencimientoTxtField.setEditable(false);
        fechaVencimientoTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fechaVencimientoTxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(fechaVencimientoTxtField, gridBagConstraints);

        formaPagolbl.setText("Forma de pago");
        formaPagolbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        datosFacturaCuerpoPanel.add(formaPagolbl, gridBagConstraints);

        formaPagoComboBox.setModel(new DefaultComboBoxModel(controller.FORMAS_PAGO));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(formaPagoComboBox, gridBagConstraints);

        facturaPanel.add(datosFacturaCuerpoPanel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel.add(facturaPanel, gridBagConstraints);

        clientePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        clientePanel.setLayout(new java.awt.BorderLayout());

        datosClientePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        datosClientePanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel5.setMinimumSize(new java.awt.Dimension(44, 16));
        jPanel5.setPreferredSize(new java.awt.Dimension(44, 20));
        jPanel5.setLayout(new java.awt.BorderLayout());

        clienteTitulolbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        clienteTitulolbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clienteTitulolbl.setText("CLIENTE");
        clienteTitulolbl.setFocusable(false);
        clienteTitulolbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        clienteTitulolbl.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel5.add(clienteTitulolbl, java.awt.BorderLayout.WEST);

        nombreClienteSearchBtn.setToolTipText("Buscar...");
        nombreClienteSearchBtn.setAlignmentX(0.5F);
        nombreClienteSearchBtn.setFocusable(false);
        nombreClienteSearchBtn.setOpaque(true);
        nombreClienteSearchBtn.setPreferredSize(new java.awt.Dimension(30, 22));
        nombreClienteSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteSearchBtnActionPerformed(evt);
            }
        });
        jPanel5.add(nombreClienteSearchBtn, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel2.add(jPanel5, gridBagConstraints);

        numeroClienteTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numeroClienteTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroClienteTxtFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel2.add(numeroClienteTxtField, gridBagConstraints);

        datosClientePanel.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(204, 88));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        nombreClientelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreClientelbl.setText("Nombre");
        nombreClientelbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        jPanel4.add(nombreClientelbl, gridBagConstraints);

        nombreClienteTxtField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(nombreClienteTxtField, gridBagConstraints);

        nifClientelbl.setText("NIF");
        nifClientelbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(nifClientelbl, gridBagConstraints);

        nifClienteTxtField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(nifClienteTxtField, gridBagConstraints);

        direccionClientelbl.setText("Dirección");
        direccionClientelbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(direccionClientelbl, gridBagConstraints);

        direccionClienteTxtField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(direccionClienteTxtField, gridBagConstraints);

        codigoPostalClientelbl.setText("Código postal");
        codigoPostalClientelbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(codigoPostalClientelbl, gridBagConstraints);

        codigoPostalClienteTxtField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel4.add(codigoPostalClienteTxtField, gridBagConstraints);

        datosClientePanel.add(jPanel4, java.awt.BorderLayout.CENTER);

        clientePanel.add(datosClientePanel, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new java.awt.GridBagLayout());
        clientePanel.add(jPanel3, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel.add(clientePanel, gridBagConstraints);

        msgPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        msgPanel.setLayout(new java.awt.GridBagLayout());

        msgContainerPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        msgContainerPanel.setFocusable(false);
        msgContainerPanel.setLayout(new java.awt.GridBagLayout());

        msgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        msgContainerPanel.add(msgLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        msgPanel.add(msgContainerPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 10);
        jPanel.add(msgPanel, gridBagConstraints);

        facturacionPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        facturacionPanel.setMinimumSize(new java.awt.Dimension(585, 199));
        facturacionPanel.setLayout(new java.awt.BorderLayout());

        facturacionTituloPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        facturacionTitulolbl.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        facturacionTitulolbl.setText("FACTURACIÓN");
        facturacionTituloPanel.add(facturacionTitulolbl);

        facturacionPanel.add(facturacionTituloPanel, java.awt.BorderLayout.NORTH);

        conceptosPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        conceptosPanel.setLayout(new java.awt.GridBagLayout());

        conceptosTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conceptosTituloLabel.setText("Concepto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(conceptosTituloLabel, gridBagConstraints);

        cantidadTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadTituloLabel.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(cantidadTituloLabel, gridBagConstraints);

        precioTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioTituloLabel.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(precioTituloLabel, gridBagConstraints);

        totalImporteTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalImporteTituloLabel.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(totalImporteTituloLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto1TxtField, gridBagConstraints);

        cantidad1TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad1TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad1TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad1TxtField, gridBagConstraints);

        precio1TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio1TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio1TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio1TxtField, gridBagConstraints);

        totalImporte1TxtField.setEditable(false);
        totalImporte1TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte1TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto2TxtField, gridBagConstraints);

        cantidad2TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad2TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad2TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad2TxtField, gridBagConstraints);

        precio2TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio2TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio2TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio2TxtField, gridBagConstraints);

        totalImporte2TxtField.setEditable(false);
        totalImporte2TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte2TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto3TxtField, gridBagConstraints);

        cantidad3TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad3TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad3TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad3TxtField, gridBagConstraints);

        precio3TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio3TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio3TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio3TxtField, gridBagConstraints);

        totalImporte3TxtField.setEditable(false);
        totalImporte3TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte3TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto4TxtField, gridBagConstraints);

        cantidad4TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad4TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad4TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad4TxtField, gridBagConstraints);

        precio4TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio4TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio4TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio4TxtField, gridBagConstraints);

        totalImporte4TxtField.setEditable(false);
        totalImporte4TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte4TxtField, gridBagConstraints);

        idiomaOrigenTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idiomaOrigenTituloLabel.setText("Idiom. Orig.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(idiomaOrigenTituloLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen1TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen2TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen3TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen4TxtField, gridBagConstraints);

        idiomaDestinoTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idiomaDestinoTituloLabel.setText("Idiom. Dest.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(idiomaDestinoTituloLabel, gridBagConstraints);

        idiomaDestino1TxtField.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino1TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino2TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino3TxtField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino4TxtField, gridBagConstraints);

        TipoTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TipoTituloLabel.setText("Unidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(TipoTituloLabel, gridBagConstraints);

        item1ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item1ComboBox, gridBagConstraints);

        item2ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item2ComboBox, gridBagConstraints);

        item3ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item3ComboBox, gridBagConstraints);

        item4ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item4ComboBox, gridBagConstraints);

        facturacionPanel.add(conceptosPanel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel.add(facturacionPanel, gridBagConstraints);

        buttonsPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        verificarFichaBtn.setText("Verificar");
        verificarFichaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarFichaBtnItemClicked(evt);
            }
        });
        buttonsPanel.add(verificarFichaBtn);

        previewFacturaBtn.setText("Preview Factura");
        previewFacturaBtn.setEnabled(false);
        previewFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewFacturaBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(previewFacturaBtn);

        registrarFacturaBtn.setText("Registrar y Guardar Factura");
        registrarFacturaBtn.setEnabled(false);
        registrarFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarFacturaBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(registrarFacturaBtn);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel.add(buttonsPanel, gridBagConstraints);

        getContentPane().add(jPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void precio1TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio1TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio1TxtField, cantidad1TxtField, totalImporte1TxtField);
    }//GEN-LAST:event_precio1TxtFieldKeyReleased

    private void cantidad1TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad1TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad1TxtField, precio1TxtField, totalImporte1TxtField);
    }//GEN-LAST:event_cantidad1TxtFieldKeyReleased

    private void cantidad2TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad2TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad2TxtField, precio2TxtField, totalImporte2TxtField);
    }//GEN-LAST:event_cantidad2TxtFieldKeyReleased

    private void precio2TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio2TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio2TxtField, cantidad2TxtField, totalImporte2TxtField);
    }//GEN-LAST:event_precio2TxtFieldKeyReleased

    private void cantidad3TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad3TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad3TxtField, precio3TxtField, totalImporte3TxtField);
    }//GEN-LAST:event_cantidad3TxtFieldKeyReleased

    private void precio3TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio3TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio3TxtField, cantidad3TxtField, totalImporte3TxtField);
    }//GEN-LAST:event_precio3TxtFieldKeyReleased

    private void cantidad4TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad4TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad4TxtField, precio4TxtField, totalImporte4TxtField);
    }//GEN-LAST:event_cantidad4TxtFieldKeyReleased

    private void precio4TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio4TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio4TxtField, cantidad4TxtField, totalImporte4TxtField);
    }//GEN-LAST:event_precio4TxtFieldKeyReleased

    private void diasParaPagoTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diasParaPagoTxtFieldKeyReleased
        controller.calculaFechaVencimiento(fechaEmisionTxtField, diasParaPagoTxtField, fechaVencimientoTxtField);
    }//GEN-LAST:event_diasParaPagoTxtFieldKeyReleased

    private void fechaEmisionTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaEmisionTxtFieldKeyReleased
        controller.calculaFechaVencimiento(fechaEmisionTxtField, diasParaPagoTxtField, fechaVencimientoTxtField);
    }//GEN-LAST:event_fechaEmisionTxtFieldKeyReleased

    private void previewFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewFacturaBtnActionPerformed
        controller.previewFacturaBtnPulsado();
    }//GEN-LAST:event_previewFacturaBtnActionPerformed

    private void registrarFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarFacturaBtnActionPerformed
        controller.registraFactura();
    }//GEN-LAST:event_registrarFacturaBtnActionPerformed

    private void nombreClienteSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteSearchBtnActionPerformed
        controller.abrirClienteLookupFrame();
    }//GEN-LAST:event_nombreClienteSearchBtnActionPerformed

    private void numeroClienteTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroClienteTxtFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            controller.cargaDatosDeNumeroCliente();
        }
    }//GEN-LAST:event_numeroClienteTxtFieldKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controller.closeView();
    }//GEN-LAST:event_formWindowClosed

    private void verificarFichaBtnItemClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarFichaBtnItemClicked
        controller.gestionaToggleButtonVerificarDatos();
    }//GEN-LAST:event_verificarFichaBtnItemClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel TipoTituloLabel;
    public javax.swing.JPanel buttonsPanel;
    public javax.swing.JTextField cantidad1TxtField;
    public javax.swing.JTextField cantidad2TxtField;
    public javax.swing.JTextField cantidad3TxtField;
    public javax.swing.JTextField cantidad4TxtField;
    public javax.swing.JLabel cantidadTituloLabel;
    public javax.swing.JPanel clientePanel;
    public javax.swing.JLabel clienteTitulolbl;
    public javax.swing.JTextField codigoPostalClienteTxtField;
    public javax.swing.JLabel codigoPostalClientelbl;
    public javax.swing.JTextField concepto1TxtField;
    public javax.swing.JTextField concepto2TxtField;
    public javax.swing.JTextField concepto3TxtField;
    public javax.swing.JTextField concepto4TxtField;
    public javax.swing.JPanel conceptosPanel;
    public javax.swing.JLabel conceptosTituloLabel;
    public javax.swing.JPanel datosClientePanel;
    public javax.swing.JPanel datosFacturaCuerpoPanel;
    public javax.swing.JPanel datosFacturaTitulolbl;
    public javax.swing.JTextField diasParaPagoTxtField;
    public javax.swing.JLabel diasParaPagolbl;
    public javax.swing.JTextField direccionClienteTxtField;
    public javax.swing.JLabel direccionClientelbl;
    public javax.swing.JPanel facturaPanel;
    public javax.swing.JPanel facturacionPanel;
    public javax.swing.JPanel facturacionTituloPanel;
    public javax.swing.JLabel facturacionTitulolbl;
    public javax.swing.JTextField fechaEmisionTxtField;
    public javax.swing.JLabel fechaEmisionlbl;
    public javax.swing.JTextField fechaVencimientoTxtField;
    public javax.swing.JLabel fechaVencimientolbl;
    public javax.swing.JComboBox<String> formaPagoComboBox;
    public javax.swing.JLabel formaPagolbl;
    public javax.swing.JTextField idiomaDestino1TxtField;
    public javax.swing.JTextField idiomaDestino2TxtField;
    public javax.swing.JTextField idiomaDestino3TxtField;
    public javax.swing.JTextField idiomaDestino4TxtField;
    public javax.swing.JLabel idiomaDestinoTituloLabel;
    public javax.swing.JTextField idiomaOrigen1TxtField;
    public javax.swing.JTextField idiomaOrigen2TxtField;
    public javax.swing.JTextField idiomaOrigen3TxtField;
    public javax.swing.JTextField idiomaOrigen4TxtField;
    public javax.swing.JLabel idiomaOrigenTituloLabel;
    public javax.swing.JComboBox<String> item1ComboBox;
    public javax.swing.JComboBox<String> item2ComboBox;
    public javax.swing.JComboBox<String> item3ComboBox;
    public javax.swing.JComboBox<String> item4ComboBox;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel msgContainerPanel;
    public javax.swing.JLabel msgLbl;
    public javax.swing.JPanel msgPanel;
    public javax.swing.JTextField nifClienteTxtField;
    public javax.swing.JLabel nifClientelbl;
    public javax.swing.JButton nombreClienteSearchBtn;
    public javax.swing.JTextField nombreClienteTxtField;
    public javax.swing.JLabel nombreClientelbl;
    public javax.swing.JTextField numeroClienteTxtField;
    public javax.swing.JTextField numeroFraTxtField;
    public javax.swing.JLabel numeroFralbl;
    public javax.swing.JTextField precio1TxtField;
    public javax.swing.JTextField precio2TxtField;
    public javax.swing.JTextField precio3TxtField;
    public javax.swing.JTextField precio4TxtField;
    public javax.swing.JLabel precioTituloLabel;
    public javax.swing.JButton previewFacturaBtn;
    public javax.swing.JButton registrarFacturaBtn;
    public javax.swing.JTextField totalImporte1TxtField;
    public javax.swing.JTextField totalImporte2TxtField;
    public javax.swing.JTextField totalImporte3TxtField;
    public javax.swing.JTextField totalImporte4TxtField;
    public javax.swing.JLabel totalImporteTituloLabel;
    public javax.swing.JToggleButton verificarFichaBtn;
    // End of variables declaration//GEN-END:variables

}
