/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jud.gestorfacturas.gui.view;

import jud.gestorfacturas.gui.controller.FrameContainerController;

/**
 *
 * @author nooko
 */
public class FrameContainerView extends javax.swing.JFrame {

    FrameContainerController controller;
    
    public FrameContainerView(FrameContainerController _controller, String title) {
        this.controller = _controller;
        initComponents();
        this.setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        nuevoMenu = new javax.swing.JMenu();
        nuevaFacturaItemMenu = new javax.swing.JMenuItem();
        crearClienteItemMenu = new javax.swing.JMenuItem();
        editarMenu = new javax.swing.JMenu();
        editarClienteItemMenu = new javax.swing.JMenuItem();
        editarDatosPersonalesItemMenu = new javax.swing.JMenuItem();
        buscarMenu = new javax.swing.JMenu();
        buscarFacturaItemMenu = new javax.swing.JMenuItem();
        herramientasMenu = new javax.swing.JMenu();
        origenDatosItemMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoMenu.setMnemonic('n');
        nuevoMenu.setText("Nuevo");

        nuevaFacturaItemMenu.setMnemonic('f');
        nuevaFacturaItemMenu.setText("Nueva factura...");
        nuevaFacturaItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaFacturaItemMenuActionPerformed(evt);
            }
        });
        nuevoMenu.add(nuevaFacturaItemMenu);

        crearClienteItemMenu.setMnemonic('c');
        crearClienteItemMenu.setText("Crear cliente...");
        crearClienteItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteItemMenuActionPerformed(evt);
            }
        });
        nuevoMenu.add(crearClienteItemMenu);

        jMenuBar1.add(nuevoMenu);

        editarMenu.setMnemonic('e');
        editarMenu.setText("Editar");

        editarClienteItemMenu.setMnemonic('c');
        editarClienteItemMenu.setText("Editar cliente...");
        editarClienteItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClienteItemMenuActionPerformed(evt);
            }
        });
        editarMenu.add(editarClienteItemMenu);

        editarDatosPersonalesItemMenu.setMnemonic('p');
        editarDatosPersonalesItemMenu.setText("Editar datos personales...");
        editarDatosPersonalesItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDatosPersonalesItemMenuActionPerformed(evt);
            }
        });
        editarMenu.add(editarDatosPersonalesItemMenu);

        jMenuBar1.add(editarMenu);

        buscarMenu.setMnemonic('b');
        buscarMenu.setText("Buscar");

        buscarFacturaItemMenu.setMnemonic('f');
        buscarFacturaItemMenu.setText("Buscar factura...");
        buscarFacturaItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFacturaItemMenuActionPerformed(evt);
            }
        });
        buscarMenu.add(buscarFacturaItemMenu);

        jMenuBar1.add(buscarMenu);

        herramientasMenu.setMnemonic('h');
        herramientasMenu.setText("Herramientas");

        origenDatosItemMenu.setMnemonic('d');
        origenDatosItemMenu.setText("Origen de datos...");
        origenDatosItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenDatosItemMenuActionPerformed(evt);
            }
        });
        herramientasMenu.add(origenDatosItemMenu);

        jMenuBar1.add(herramientasMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaFacturaItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaFacturaItemMenuActionPerformed
        controller.openNuevaFactura();
    }//GEN-LAST:event_nuevaFacturaItemMenuActionPerformed

    private void crearClienteItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteItemMenuActionPerformed
        controller.openCrearCliente();
    }//GEN-LAST:event_crearClienteItemMenuActionPerformed

    private void editarClienteItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClienteItemMenuActionPerformed
        controller.openModificarCliente();
    }//GEN-LAST:event_editarClienteItemMenuActionPerformed

    private void editarDatosPersonalesItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDatosPersonalesItemMenuActionPerformed
        controller.openDatosPersonales();
    }//GEN-LAST:event_editarDatosPersonalesItemMenuActionPerformed

    private void origenDatosItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenDatosItemMenuActionPerformed
        controller.openConfiguracion();
    }//GEN-LAST:event_origenDatosItemMenuActionPerformed

    private void buscarFacturaItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFacturaItemMenuActionPerformed
        controller.openBuscarFactura();
    }//GEN-LAST:event_buscarFacturaItemMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameContainerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameContainerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameContainerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameContainerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarFacturaItemMenu;
    private javax.swing.JMenu buscarMenu;
    private javax.swing.JMenuItem crearClienteItemMenu;
    private javax.swing.JMenuItem editarClienteItemMenu;
    private javax.swing.JMenuItem editarDatosPersonalesItemMenu;
    private javax.swing.JMenu editarMenu;
    private javax.swing.JMenu herramientasMenu;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem nuevaFacturaItemMenu;
    private javax.swing.JMenu nuevoMenu;
    private javax.swing.JMenuItem origenDatosItemMenu;
    // End of variables declaration//GEN-END:variables
}
