
package jud.gestorfacturas.gui.view;

import jud.gestorfacturas.gui.controller.FacturaController;
import jud.gestorfacturas.gui.controller.InvoiceLookupController;
import jud.gestorfacturas.gui.controller.MainMenuController;
import jud.gestorfacturas.gui.controller.ModificarClienteController;
import jud.gestorfacturas.gui.controller.ModificarEmisorController;
import jud.gestorfacturas.gui.controller.NuevoClienteController;

public class MainMenuView extends javax.swing.JFrame {

    MainMenuController controller;
    
    public MainMenuView(MainMenuController _controller) {
        this.controller = _controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        crearFacturaBtn = new javax.swing.JButton();
        modificarClienteBtn = new javax.swing.JButton();
        crearClienteBtn = new javax.swing.JButton();
        datosPropiosBtn = new javax.swing.JButton();
        listarFacturasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");
        setPreferredSize(new java.awt.Dimension(300, 240));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        crearFacturaBtn.setText("Crear factura");
        crearFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearFacturaBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(crearFacturaBtn, gridBagConstraints);

        modificarClienteBtn.setText("Modificar cliente");
        modificarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarClienteBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(modificarClienteBtn, gridBagConstraints);

        crearClienteBtn.setText("Crear cliente");
        crearClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(crearClienteBtn, gridBagConstraints);

        datosPropiosBtn.setText("Datos propios");
        datosPropiosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosPropiosBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(datosPropiosBtn, gridBagConstraints);

        listarFacturasBtn.setText("Lista de facturas");
        listarFacturasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFacturasBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(listarFacturasBtn, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearFacturaBtnActionPerformed
        FacturaController fc = new FacturaController(controller);
        this.setVisible(false);
    }//GEN-LAST:event_crearFacturaBtnActionPerformed

    private void crearClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteBtnActionPerformed
        NuevoClienteController ncc = new NuevoClienteController(controller);
        this.setVisible(false);
    }//GEN-LAST:event_crearClienteBtnActionPerformed

    private void modificarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarClienteBtnActionPerformed
        ModificarClienteController mcc = new ModificarClienteController(controller);
        this.setVisible(false);
    }//GEN-LAST:event_modificarClienteBtnActionPerformed

    private void datosPropiosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosPropiosBtnActionPerformed
        ModificarEmisorController mec = new ModificarEmisorController(controller);
        this.setVisible(false);
    }//GEN-LAST:event_datosPropiosBtnActionPerformed

    private void listarFacturasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFacturasBtnActionPerformed
        InvoiceLookupController il = new InvoiceLookupController(controller);
        this.setVisible(false);
    }//GEN-LAST:event_listarFacturasBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton crearClienteBtn;
    public javax.swing.JButton crearFacturaBtn;
    public javax.swing.JButton datosPropiosBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listarFacturasBtn;
    public javax.swing.JButton modificarClienteBtn;
    // End of variables declaration//GEN-END:variables

}
