
package jud.gestorfacturas.gui.crear;

import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class CrearFacturaView extends javax.swing.JPanel {

    CrearFacturaController controller;
    
    public CrearFacturaView(CrearFacturaController _controller) {
        controller = _controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        facturaPanel1 = new javax.swing.JPanel();
        datosFacturaTitulolbl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        datosFacturaCuerpoPanel = new javax.swing.JPanel();
        numeroFralbl = new javax.swing.JLabel();
        numeroFraTxtField = new javax.swing.JTextField();
        fechaEmisionlbl = new javax.swing.JLabel();
        fechaEmisionTxtField = new javax.swing.JTextField();
        diasParaPagolbl = new javax.swing.JLabel();
        diasParaPagoTxtField = new javax.swing.JTextField();
        fechaVencimientolbl = new javax.swing.JLabel();
        fechaVencimientoTxtField = new javax.swing.JTextField();
        formaPagolbl = new javax.swing.JLabel();
        formaPagoComboBox = new javax.swing.JComboBox<>();
        clientePanel = new javax.swing.JPanel();
        datosClientePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        clienteTitulolbl1 = new javax.swing.JLabel();
        clienteSearchBtn = new javax.swing.JButton();
        numeroClienteTxtField = new javax.swing.JTextField();
        clienteEraseBtn = new javax.swing.JButton();
        clienteInfoTxtFieldPanel = new javax.swing.JPanel();
        nombreClientelbl1 = new javax.swing.JLabel();
        nombreClienteTxtField = new javax.swing.JTextField();
        nifClientelbl1 = new javax.swing.JLabel();
        nifClienteTxtField = new javax.swing.JTextField();
        direccionClientelbl1 = new javax.swing.JLabel();
        direccionClienteTxtField = new javax.swing.JTextField();
        codigoPostalClientelbl1 = new javax.swing.JLabel();
        codigoPostalClienteTxtField = new javax.swing.JTextField();
        msgPanel1 = new javax.swing.JPanel();
        msgContainerPanel1 = new javax.swing.JPanel();
        msgLbl = new javax.swing.JLabel();
        facturacionPanel1 = new javax.swing.JPanel();
        facturacionTituloPanel = new javax.swing.JPanel();
        facturacionTitulolbl1 = new javax.swing.JLabel();
        conceptosPanel = new javax.swing.JPanel();
        conceptosTituloLabel = new javax.swing.JLabel();
        cantidadTituloLabel = new javax.swing.JLabel();
        precioTituloLabel = new javax.swing.JLabel();
        totalImporteTituloLabel = new javax.swing.JLabel();
        concepto1TxtField = new javax.swing.JTextField();
        cantidad1TxtField = new javax.swing.JTextField();
        precio1TxtField = new javax.swing.JTextField();
        totalImporte1TxtField = new javax.swing.JTextField();
        concepto2TxtField = new javax.swing.JTextField();
        cantidad2TxtField = new javax.swing.JTextField();
        precio2TxtField = new javax.swing.JTextField();
        totalImporte2TxtField = new javax.swing.JTextField();
        concepto3TxtField = new javax.swing.JTextField();
        cantidad3TxtField = new javax.swing.JTextField();
        precio3TxtField = new javax.swing.JTextField();
        totalImporte3TxtField = new javax.swing.JTextField();
        concepto4TxtField = new javax.swing.JTextField();
        cantidad4TxtField = new javax.swing.JTextField();
        precio4TxtField = new javax.swing.JTextField();
        totalImporte4TxtField = new javax.swing.JTextField();
        idiomaOrigenTituloLabel = new javax.swing.JLabel();
        idiomaOrigen1TxtField = new javax.swing.JTextField();
        idiomaOrigen2TxtField = new javax.swing.JTextField();
        idiomaOrigen3TxtField = new javax.swing.JTextField();
        idiomaOrigen4TxtField = new javax.swing.JTextField();
        idiomaDestinoTituloLabel = new javax.swing.JLabel();
        idiomaDestino1TxtField = new javax.swing.JTextField();
        idiomaDestino2TxtField = new javax.swing.JTextField();
        idiomaDestino3TxtField = new javax.swing.JTextField();
        idiomaDestino4TxtField = new javax.swing.JTextField();
        TipoTituloLabel = new javax.swing.JLabel();
        item1ComboBox = new javax.swing.JComboBox<>();
        item2ComboBox = new javax.swing.JComboBox<>();
        item3ComboBox = new javax.swing.JComboBox<>();
        item4ComboBox = new javax.swing.JComboBox<>();
        buttonsPanel = new javax.swing.JPanel();
        refrescarFacturaBtn = new javax.swing.JButton();
        verificarFichaBtn = new javax.swing.JButton();
        previewFacturaBtn = new javax.swing.JButton();
        registrarFacturaBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 401));

        facturaPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        facturaPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        facturaPanel1.setLayout(new java.awt.BorderLayout());

        datosFacturaTitulolbl.setFocusable(false);
        datosFacturaTitulolbl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("FACTURA");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        datosFacturaTitulolbl.add(jLabel2);

        facturaPanel1.add(datosFacturaTitulolbl, java.awt.BorderLayout.NORTH);

        datosFacturaCuerpoPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        datosFacturaCuerpoPanel.setLayout(new java.awt.GridBagLayout());

        numeroFralbl.setText("Número de factura");
        numeroFralbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weightx = 0.2;
        datosFacturaCuerpoPanel.add(numeroFralbl, gridBagConstraints);

        numeroFraTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeroFraTxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(numeroFraTxtField, gridBagConstraints);

        fechaEmisionlbl.setText("Fecha de emisión");
        fechaEmisionlbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        datosFacturaCuerpoPanel.add(fechaEmisionlbl, gridBagConstraints);

        fechaEmisionTxtField.setToolTipText("Son válidos cualquiera de los siguientes formatos:\ndd/MM/yyyy\ndd-MM-yyyy\ndd/MM/yy\ndd-MM-yy\nddMMyyyy\nddMMyy");
        fechaEmisionTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaEmisionTxtFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechaEmisionTxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(fechaEmisionTxtField, gridBagConstraints);

        diasParaPagolbl.setText("Días para pago");
        diasParaPagolbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        datosFacturaCuerpoPanel.add(diasParaPagolbl, gridBagConstraints);

        diasParaPagoTxtField.setToolTipText("Ha de ser un número entero");
        diasParaPagoTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                diasParaPagoTxtFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diasParaPagoTxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(diasParaPagoTxtField, gridBagConstraints);

        fechaVencimientolbl.setText("Fecha de vencimiento");
        fechaVencimientolbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        datosFacturaCuerpoPanel.add(fechaVencimientolbl, gridBagConstraints);

        fechaVencimientoTxtField.setEditable(false);
        fechaVencimientoTxtField.setBackground(new java.awt.Color(70, 73, 75));
        fechaVencimientoTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(fechaVencimientoTxtField, gridBagConstraints);

        formaPagolbl.setText("Forma de pago");
        formaPagolbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weightx = 0.2;
        datosFacturaCuerpoPanel.add(formaPagolbl, gridBagConstraints);

        formaPagoComboBox.setModel(new DefaultComboBoxModel(controller.FORMAS_PAGO));
        formaPagoComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formaPagoComboBoxMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        datosFacturaCuerpoPanel.add(formaPagoComboBox, gridBagConstraints);

        facturaPanel1.add(datosFacturaCuerpoPanel, java.awt.BorderLayout.CENTER);

        clientePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        clientePanel.setLayout(new java.awt.BorderLayout());

        datosClientePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        datosClientePanel.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(44, 16));
        jPanel7.setPreferredSize(new java.awt.Dimension(44, 20));
        jPanel7.setLayout(new java.awt.BorderLayout());

        clienteTitulolbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clienteTitulolbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clienteTitulolbl1.setText("CLIENTE");
        clienteTitulolbl1.setFocusable(false);
        clienteTitulolbl1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        clienteTitulolbl1.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel7.add(clienteTitulolbl1, java.awt.BorderLayout.WEST);

        clienteSearchBtn.setToolTipText("Buscar...");
        clienteSearchBtn.setAlignmentX(0.5F);
        clienteSearchBtn.setFocusable(false);
        clienteSearchBtn.setOpaque(true);
        clienteSearchBtn.setPreferredSize(new java.awt.Dimension(30, 22));
        clienteSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteSearchBtnActionPerformed(evt);
            }
        });
        jPanel7.add(clienteSearchBtn, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel6.add(jPanel7, gridBagConstraints);

        numeroClienteTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numeroClienteTxtField.setOpaque(true);
        numeroClienteTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numeroClienteTxtFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanel6.add(numeroClienteTxtField, gridBagConstraints);

        clienteEraseBtn.setToolTipText("Buscar...");
        clienteEraseBtn.setAlignmentX(0.5F);
        clienteEraseBtn.setFocusable(false);
        clienteEraseBtn.setOpaque(true);
        clienteEraseBtn.setPreferredSize(new java.awt.Dimension(30, 22));
        clienteEraseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteEraseBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel6.add(clienteEraseBtn, gridBagConstraints);

        datosClientePanel.add(jPanel6, java.awt.BorderLayout.NORTH);

        clienteInfoTxtFieldPanel.setPreferredSize(new java.awt.Dimension(204, 88));
        clienteInfoTxtFieldPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreClientelbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreClientelbl1.setText("Nombre");
        nombreClientelbl1.setFocusable(false);
        clienteInfoTxtFieldPanel.add(nombreClientelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 109, -1));

        nombreClienteTxtField.setEditable(false);
        nombreClienteTxtField.setBackground(new java.awt.Color(152, 152, 152));
        nombreClienteTxtField.setForeground(new java.awt.Color(0, 0, 0));
        clienteInfoTxtFieldPanel.add(nombreClienteTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 38, 183, -1));

        nifClientelbl1.setText("NIF");
        nifClientelbl1.setFocusable(false);
        clienteInfoTxtFieldPanel.add(nifClientelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 109, -1));

        nifClienteTxtField.setEditable(false);
        nifClienteTxtField.setBackground(new java.awt.Color(152, 152, 152));
        nifClienteTxtField.setForeground(new java.awt.Color(0, 0, 0));
        clienteInfoTxtFieldPanel.add(nifClienteTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 16, 183, -1));

        direccionClientelbl1.setText("Dirección");
        direccionClientelbl1.setFocusable(false);
        clienteInfoTxtFieldPanel.add(direccionClientelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 109, -1));

        direccionClienteTxtField.setEditable(false);
        direccionClienteTxtField.setBackground(new java.awt.Color(152, 152, 152));
        direccionClienteTxtField.setForeground(new java.awt.Color(0, 0, 0));
        clienteInfoTxtFieldPanel.add(direccionClienteTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 60, 183, -1));

        codigoPostalClientelbl1.setText("Código postal");
        codigoPostalClientelbl1.setFocusable(false);
        clienteInfoTxtFieldPanel.add(codigoPostalClientelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 109, -1));

        codigoPostalClienteTxtField.setEditable(false);
        codigoPostalClienteTxtField.setBackground(new java.awt.Color(152, 152, 152));
        codigoPostalClienteTxtField.setForeground(new java.awt.Color(0, 0, 0));
        clienteInfoTxtFieldPanel.add(codigoPostalClienteTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 82, 183, -1));

        datosClientePanel.add(clienteInfoTxtFieldPanel, java.awt.BorderLayout.CENTER);

        clientePanel.add(datosClientePanel, java.awt.BorderLayout.CENTER);

        msgPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        msgPanel1.setLayout(new java.awt.GridBagLayout());

        msgContainerPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        msgContainerPanel1.setFocusable(false);
        msgContainerPanel1.setLayout(new java.awt.GridBagLayout());

        msgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLbl.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        msgContainerPanel1.add(msgLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        msgPanel1.add(msgContainerPanel1, gridBagConstraints);

        facturacionPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        facturacionPanel1.setMinimumSize(new java.awt.Dimension(585, 199));
        facturacionPanel1.setLayout(new java.awt.BorderLayout());

        facturacionTituloPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        facturacionTitulolbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        facturacionTitulolbl1.setText("FACTURACIÓN");
        facturacionTituloPanel.add(facturacionTitulolbl1);

        facturacionPanel1.add(facturacionTituloPanel, java.awt.BorderLayout.NORTH);

        conceptosPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        conceptosPanel.setLayout(new java.awt.GridBagLayout());

        conceptosTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conceptosTituloLabel.setText("Concepto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(conceptosTituloLabel, gridBagConstraints);

        cantidadTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadTituloLabel.setText("Cantidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(cantidadTituloLabel, gridBagConstraints);

        precioTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioTituloLabel.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(precioTituloLabel, gridBagConstraints);

        totalImporteTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalImporteTituloLabel.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(totalImporteTituloLabel, gridBagConstraints);

        concepto1TxtField.setColumns(23);
        concepto1TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concepto1TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto1TxtField, gridBagConstraints);

        cantidad1TxtField.setColumns(6);
        cantidad1TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad1TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidad1TxtFieldMouseClicked(evt);
            }
        });
        cantidad1TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad1TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad1TxtField, gridBagConstraints);

        precio1TxtField.setColumns(5);
        precio1TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio1TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precio1TxtFieldMouseClicked(evt);
            }
        });
        precio1TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio1TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio1TxtField, gridBagConstraints);

        totalImporte1TxtField.setEditable(false);
        totalImporte1TxtField.setColumns(8);
        totalImporte1TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte1TxtField, gridBagConstraints);

        concepto2TxtField.setColumns(23);
        concepto2TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concepto2TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto2TxtField, gridBagConstraints);

        cantidad2TxtField.setColumns(6);
        cantidad2TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad2TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidad2TxtFieldMouseClicked(evt);
            }
        });
        cantidad2TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad2TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad2TxtField, gridBagConstraints);

        precio2TxtField.setColumns(5);
        precio2TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio2TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precio2TxtFieldMouseClicked(evt);
            }
        });
        precio2TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio2TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio2TxtField, gridBagConstraints);

        totalImporte2TxtField.setEditable(false);
        totalImporte2TxtField.setColumns(8);
        totalImporte2TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte2TxtField, gridBagConstraints);

        concepto3TxtField.setColumns(23);
        concepto3TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concepto3TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto3TxtField, gridBagConstraints);

        cantidad3TxtField.setColumns(6);
        cantidad3TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad3TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidad3TxtFieldMouseClicked(evt);
            }
        });
        cantidad3TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad3TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad3TxtField, gridBagConstraints);

        precio3TxtField.setColumns(5);
        precio3TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio3TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precio3TxtFieldMouseClicked(evt);
            }
        });
        precio3TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio3TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio3TxtField, gridBagConstraints);

        totalImporte3TxtField.setEditable(false);
        totalImporte3TxtField.setColumns(8);
        totalImporte3TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte3TxtField, gridBagConstraints);

        concepto4TxtField.setColumns(23);
        concepto4TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concepto4TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(concepto4TxtField, gridBagConstraints);

        cantidad4TxtField.setColumns(6);
        cantidad4TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        cantidad4TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidad4TxtFieldMouseClicked(evt);
            }
        });
        cantidad4TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidad4TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(cantidad4TxtField, gridBagConstraints);

        precio4TxtField.setColumns(5);
        precio4TxtField.setToolTipText("El formato ha de ser un número (entero o decimal) que no contenga espacios ni letras.");
        precio4TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precio4TxtFieldMouseClicked(evt);
            }
        });
        precio4TxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio4TxtFieldKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(precio4TxtField, gridBagConstraints);

        totalImporte4TxtField.setEditable(false);
        totalImporte4TxtField.setColumns(8);
        totalImporte4TxtField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(totalImporte4TxtField, gridBagConstraints);

        idiomaOrigenTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idiomaOrigenTituloLabel.setText("Idiom. Orig.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(idiomaOrigenTituloLabel, gridBagConstraints);

        idiomaOrigen1TxtField.setColumns(3);
        idiomaOrigen1TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaOrigen1TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen1TxtField, gridBagConstraints);

        idiomaOrigen2TxtField.setColumns(3);
        idiomaOrigen2TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaOrigen2TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen2TxtField, gridBagConstraints);

        idiomaOrigen3TxtField.setColumns(3);
        idiomaOrigen3TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaOrigen3TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen3TxtField, gridBagConstraints);

        idiomaOrigen4TxtField.setColumns(3);
        idiomaOrigen4TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaOrigen4TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaOrigen4TxtField, gridBagConstraints);

        idiomaDestinoTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idiomaDestinoTituloLabel.setText("Idiom. Dest.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(idiomaDestinoTituloLabel, gridBagConstraints);

        idiomaDestino1TxtField.setColumns(3);
        idiomaDestino1TxtField.setToolTipText("");
        idiomaDestino1TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaDestino1TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino1TxtField, gridBagConstraints);

        idiomaDestino2TxtField.setColumns(3);
        idiomaDestino2TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaDestino2TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino2TxtField, gridBagConstraints);

        idiomaDestino3TxtField.setColumns(3);
        idiomaDestino3TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaDestino3TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino3TxtField, gridBagConstraints);

        idiomaDestino4TxtField.setColumns(3);
        idiomaDestino4TxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idiomaDestino4TxtFieldMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(idiomaDestino4TxtField, gridBagConstraints);

        TipoTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TipoTituloLabel.setText("Unidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        conceptosPanel.add(TipoTituloLabel, gridBagConstraints);

        item1ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        item1ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1ComboBoxMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item1ComboBox, gridBagConstraints);

        item2ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        item2ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item2ComboBoxMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item2ComboBox, gridBagConstraints);

        item3ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        item3ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item3ComboBoxMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item3ComboBox, gridBagConstraints);

        item4ComboBox.setModel(new DefaultComboBoxModel(controller.TIPOS_UNIDAD));
        item4ComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item4ComboBoxMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        conceptosPanel.add(item4ComboBox, gridBagConstraints);

        facturacionPanel1.add(conceptosPanel, java.awt.BorderLayout.CENTER);

        buttonsPanel.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        refrescarFacturaBtn.setBackground(new java.awt.Color(204, 204, 204));
        refrescarFacturaBtn.setForeground(new java.awt.Color(0, 0, 0));
        refrescarFacturaBtn.setText("Nueva factura");
        refrescarFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarFacturaBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(refrescarFacturaBtn);

        verificarFichaBtn.setBackground(new java.awt.Color(255, 255, 204));
        verificarFichaBtn.setForeground(new java.awt.Color(0, 0, 0));
        verificarFichaBtn.setText("Verificar");
        verificarFichaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarFichaBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(verificarFichaBtn);

        previewFacturaBtn.setText("Visualizar factura");
        previewFacturaBtn.setEnabled(false);
        previewFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewFacturaBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(previewFacturaBtn);

        registrarFacturaBtn.setText("Registrar factura");
        registrarFacturaBtn.setEnabled(false);
        registrarFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarFacturaBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(registrarFacturaBtn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(facturaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(clientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(facturacionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facturaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facturacionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fechaEmisionTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaEmisionTxtFieldKeyReleased
        controller.calculaFechaVencimiento(fechaEmisionTxtField, diasParaPagoTxtField, fechaVencimientoTxtField);
    }//GEN-LAST:event_fechaEmisionTxtFieldKeyReleased

    private void diasParaPagoTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diasParaPagoTxtFieldKeyReleased
        controller.calculaFechaVencimiento(fechaEmisionTxtField, diasParaPagoTxtField, fechaVencimientoTxtField);
    }//GEN-LAST:event_diasParaPagoTxtFieldKeyReleased

    private void clienteSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteSearchBtnActionPerformed
        controller.abrirClienteLookupFrame();
    }//GEN-LAST:event_clienteSearchBtnActionPerformed

    private void cantidad1TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad1TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad1TxtField, precio1TxtField, totalImporte1TxtField);
    }//GEN-LAST:event_cantidad1TxtFieldKeyReleased

    private void precio1TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio1TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio1TxtField, cantidad1TxtField, totalImporte1TxtField);
    }//GEN-LAST:event_precio1TxtFieldKeyReleased

    private void cantidad2TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad2TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad2TxtField, precio2TxtField, totalImporte2TxtField);
    }//GEN-LAST:event_cantidad2TxtFieldKeyReleased

    private void precio2TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio2TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio2TxtField, cantidad2TxtField, totalImporte2TxtField);
    }//GEN-LAST:event_precio2TxtFieldKeyReleased

    private void cantidad3TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad3TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad3TxtField, precio3TxtField, totalImporte3TxtField);
    }//GEN-LAST:event_cantidad3TxtFieldKeyReleased

    private void precio3TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio3TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio3TxtField, cantidad3TxtField, totalImporte3TxtField);
    }//GEN-LAST:event_precio3TxtFieldKeyReleased

    private void cantidad4TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidad4TxtFieldKeyReleased
        controller.calculaPrecioServicio(cantidad4TxtField, precio4TxtField, totalImporte4TxtField);
    }//GEN-LAST:event_cantidad4TxtFieldKeyReleased

    private void precio4TxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio4TxtFieldKeyReleased
        controller.calculaPrecioServicio(precio4TxtField, cantidad4TxtField, totalImporte4TxtField);
    }//GEN-LAST:event_precio4TxtFieldKeyReleased

    private void previewFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewFacturaBtnActionPerformed
        controller.previewFacturaBtnPulsado();
    }//GEN-LAST:event_previewFacturaBtnActionPerformed

    private void registrarFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarFacturaBtnActionPerformed
        controller.registraFactura();
    }//GEN-LAST:event_registrarFacturaBtnActionPerformed

    private void verificarFichaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarFichaBtnActionPerformed
        controller.gestionaToggleButtonVerificarDatos();
    }//GEN-LAST:event_verificarFichaBtnActionPerformed

    private void refrescarFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarFacturaBtnActionPerformed
        controller.reiniciarView();
    }//GEN-LAST:event_refrescarFacturaBtnActionPerformed

    private void fechaEmisionTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaEmisionTxtFieldKeyPressed
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_fechaEmisionTxtFieldKeyPressed

    private void diasParaPagoTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diasParaPagoTxtFieldKeyPressed
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_diasParaPagoTxtFieldKeyPressed

    private void formaPagoComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formaPagoComboBoxMouseClicked
        controller.setDefaultBackground((JComboBox)evt.getSource());
    }//GEN-LAST:event_formaPagoComboBoxMouseClicked

    private void numeroFraTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroFraTxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_numeroFraTxtFieldMouseClicked

    private void concepto1TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concepto1TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_concepto1TxtFieldMouseClicked

    private void idiomaOrigen1TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaOrigen1TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaOrigen1TxtFieldMouseClicked

    private void idiomaDestino1TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaDestino1TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaDestino1TxtFieldMouseClicked

    private void cantidad1TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidad1TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_cantidad1TxtFieldMouseClicked

    private void precio1TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precio1TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_precio1TxtFieldMouseClicked

    private void item1ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1ComboBoxMouseClicked
        controller.setDefaultBackground((JComboBox)evt.getSource());
    }//GEN-LAST:event_item1ComboBoxMouseClicked

    private void concepto2TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concepto2TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_concepto2TxtFieldMouseClicked

    private void idiomaOrigen2TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaOrigen2TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaOrigen2TxtFieldMouseClicked

    private void idiomaDestino2TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaDestino2TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaDestino2TxtFieldMouseClicked

    private void cantidad2TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidad2TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_cantidad2TxtFieldMouseClicked

    private void precio2TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precio2TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_precio2TxtFieldMouseClicked

    private void item2ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item2ComboBoxMouseClicked
        controller.setDefaultBackground((JComboBox)evt.getSource());
    }//GEN-LAST:event_item2ComboBoxMouseClicked

    private void concepto3TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concepto3TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_concepto3TxtFieldMouseClicked

    private void idiomaOrigen3TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaOrigen3TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaOrigen3TxtFieldMouseClicked

    private void idiomaDestino3TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaDestino3TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaDestino3TxtFieldMouseClicked

    private void cantidad3TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidad3TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_cantidad3TxtFieldMouseClicked

    private void precio3TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precio3TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_precio3TxtFieldMouseClicked

    private void item3ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item3ComboBoxMouseClicked
        controller.setDefaultBackground((JComboBox)evt.getSource());
    }//GEN-LAST:event_item3ComboBoxMouseClicked

    private void concepto4TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concepto4TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_concepto4TxtFieldMouseClicked

    private void idiomaOrigen4TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaOrigen4TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaOrigen4TxtFieldMouseClicked

    private void idiomaDestino4TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idiomaDestino4TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_idiomaDestino4TxtFieldMouseClicked

    private void cantidad4TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidad4TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_cantidad4TxtFieldMouseClicked

    private void precio4TxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precio4TxtFieldMouseClicked
        controller.setDefaultBackground((JTextField)evt.getSource());
    }//GEN-LAST:event_precio4TxtFieldMouseClicked

    private void item4ComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item4ComboBoxMouseClicked
        controller.setDefaultBackground((JComboBox)evt.getSource());
    }//GEN-LAST:event_item4ComboBoxMouseClicked

    private void clienteEraseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteEraseBtnActionPerformed
        controller.clearDatosCliente();
    }//GEN-LAST:event_clienteEraseBtnActionPerformed

    private void numeroClienteTxtFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroClienteTxtFieldKeyPressed
        controller.toggleNumeroClienteEntered(evt);
    }//GEN-LAST:event_numeroClienteTxtFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TipoTituloLabel;
    public javax.swing.JPanel buttonsPanel;
    public javax.swing.JTextField cantidad1TxtField;
    public javax.swing.JTextField cantidad2TxtField;
    public javax.swing.JTextField cantidad3TxtField;
    public javax.swing.JTextField cantidad4TxtField;
    private javax.swing.JLabel cantidadTituloLabel;
    public javax.swing.JButton clienteEraseBtn;
    public javax.swing.JPanel clienteInfoTxtFieldPanel;
    public javax.swing.JPanel clientePanel;
    public javax.swing.JButton clienteSearchBtn;
    private javax.swing.JLabel clienteTitulolbl1;
    public javax.swing.JTextField codigoPostalClienteTxtField;
    private javax.swing.JLabel codigoPostalClientelbl1;
    public javax.swing.JTextField concepto1TxtField;
    public javax.swing.JTextField concepto2TxtField;
    public javax.swing.JTextField concepto3TxtField;
    public javax.swing.JTextField concepto4TxtField;
    public javax.swing.JPanel conceptosPanel;
    private javax.swing.JLabel conceptosTituloLabel;
    public javax.swing.JPanel datosClientePanel;
    public javax.swing.JPanel datosFacturaCuerpoPanel;
    public javax.swing.JPanel datosFacturaTitulolbl;
    public javax.swing.JTextField diasParaPagoTxtField;
    private javax.swing.JLabel diasParaPagolbl;
    public javax.swing.JTextField direccionClienteTxtField;
    private javax.swing.JLabel direccionClientelbl1;
    public javax.swing.JPanel facturaPanel1;
    public javax.swing.JPanel facturacionPanel1;
    public javax.swing.JPanel facturacionTituloPanel;
    private javax.swing.JLabel facturacionTitulolbl1;
    public javax.swing.JTextField fechaEmisionTxtField;
    private javax.swing.JLabel fechaEmisionlbl;
    public javax.swing.JTextField fechaVencimientoTxtField;
    private javax.swing.JLabel fechaVencimientolbl;
    public javax.swing.JComboBox<String> formaPagoComboBox;
    private javax.swing.JLabel formaPagolbl;
    public javax.swing.JTextField idiomaDestino1TxtField;
    public javax.swing.JTextField idiomaDestino2TxtField;
    public javax.swing.JTextField idiomaDestino3TxtField;
    public javax.swing.JTextField idiomaDestino4TxtField;
    private javax.swing.JLabel idiomaDestinoTituloLabel;
    public javax.swing.JTextField idiomaOrigen1TxtField;
    public javax.swing.JTextField idiomaOrigen2TxtField;
    public javax.swing.JTextField idiomaOrigen3TxtField;
    public javax.swing.JTextField idiomaOrigen4TxtField;
    private javax.swing.JLabel idiomaOrigenTituloLabel;
    public javax.swing.JComboBox<String> item1ComboBox;
    public javax.swing.JComboBox<String> item2ComboBox;
    public javax.swing.JComboBox<String> item3ComboBox;
    public javax.swing.JComboBox<String> item4ComboBox;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel msgContainerPanel1;
    public javax.swing.JLabel msgLbl;
    public javax.swing.JPanel msgPanel1;
    public javax.swing.JTextField nifClienteTxtField;
    private javax.swing.JLabel nifClientelbl1;
    public javax.swing.JTextField nombreClienteTxtField;
    private javax.swing.JLabel nombreClientelbl1;
    public javax.swing.JTextField numeroClienteTxtField;
    public javax.swing.JTextField numeroFraTxtField;
    private javax.swing.JLabel numeroFralbl;
    public javax.swing.JTextField precio1TxtField;
    public javax.swing.JTextField precio2TxtField;
    public javax.swing.JTextField precio3TxtField;
    public javax.swing.JTextField precio4TxtField;
    private javax.swing.JLabel precioTituloLabel;
    public javax.swing.JButton previewFacturaBtn;
    public javax.swing.JButton refrescarFacturaBtn;
    public javax.swing.JButton registrarFacturaBtn;
    public javax.swing.JTextField totalImporte1TxtField;
    public javax.swing.JTextField totalImporte2TxtField;
    public javax.swing.JTextField totalImporte3TxtField;
    public javax.swing.JTextField totalImporte4TxtField;
    private javax.swing.JLabel totalImporteTituloLabel;
    public javax.swing.JButton verificarFichaBtn;
    // End of variables declaration//GEN-END:variables
}
