
package jud.gestorfacturas.gui.configuracion;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JSpinner;

public class ConfigFacturaView extends javax.swing.JPanel {

    ConfigFacturaController controller;
    
    public ConfigFacturaView(ConfigFacturaController _controller) {
        this.controller = _controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logoLbl = new javax.swing.JLabel();
        logoPathPanel = new javax.swing.JPanel();
        firstRowAparienciaLblPanel = new javax.swing.JPanel();
        firstRowAparienciaLbl = new javax.swing.JLabel();
        firstRowAparienciaConfigPanel = new javax.swing.JPanel();
        firstRowExaminarBtn = new javax.swing.JButton();
        firstRowNombreArchivoLogoLbl = new javax.swing.JLabel();
        logoDimensionesPanel = new javax.swing.JPanel();
        secondRowAparienciaLblPanel = new javax.swing.JPanel();
        secondRowAparienciaLbl = new javax.swing.JLabel();
        firstRowConfigPanel = new javax.swing.JPanel();
        logoSizeLblPanel = new javax.swing.JPanel();
        firstRowNombreArchivoLogoPosXLbl = new javax.swing.JLabel();
        firstRowNombreArchivoLogoPosYLbl = new javax.swing.JLabel();
        firstRowNombreArchivoLogoAnchoLbl = new javax.swing.JLabel();
        firstRowNombreArchivoLogoAlturaLbl = new javax.swing.JLabel();
        logoSizeSpinnerPanel = new javax.swing.JPanel();
        logoPosXSpinner = new javax.swing.JSpinner();
        logoPosYSpinner = new javax.swing.JSpinner();
        logoAnchoSpinner = new javax.swing.JSpinner();
        logoAlturaSpinner = new javax.swing.JSpinner();
        facturacionLbl = new javax.swing.JLabel();
        precioUnitarioNumDecimalesPanel = new javax.swing.JPanel();
        rowCantidadesPanel1 = new javax.swing.JPanel();
        mostrarSiempreDecimalesLabel1 = new javax.swing.JLabel();
        decimalesPrecioJSpinner = new javax.swing.JSpinner();
        questionMarkImgLbl = new javax.swing.JLabel();
        cantidadDecimalesPanel = new javax.swing.JPanel();
        rowCantidadesPanel = new javax.swing.JPanel();
        mostrarSiempreDecimalesLabel = new javax.swing.JLabel();
        mostrarSiempreDecimalesCheckBox = new javax.swing.JCheckBox();

        logoLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoLbl.setText("LOGO");

        logoPathPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstRowAparienciaLblPanel.setLayout(new java.awt.BorderLayout());

        firstRowAparienciaLbl.setText("Logo utilizado en facturas");
        firstRowAparienciaLblPanel.add(firstRowAparienciaLbl, java.awt.BorderLayout.CENTER);

        logoPathPanel.add(firstRowAparienciaLblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 35));

        firstRowAparienciaConfigPanel.setLayout(new java.awt.GridBagLayout());

        firstRowExaminarBtn.setText("Examinar...");
        firstRowExaminarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        firstRowExaminarBtn.setName("factura.logo.path"); // NOI18N
        firstRowExaminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstRowExaminarBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        firstRowAparienciaConfigPanel.add(firstRowExaminarBtn, gridBagConstraints);

        firstRowNombreArchivoLogoLbl.setText("nombreArchivo.ext");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        firstRowAparienciaConfigPanel.add(firstRowNombreArchivoLogoLbl, gridBagConstraints);

        logoPathPanel.add(firstRowAparienciaConfigPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, -4, 250, 40));

        logoDimensionesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondRowAparienciaLblPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondRowAparienciaLbl.setText("Dimensiones del logo en la factura");
        secondRowAparienciaLblPanel.add(secondRowAparienciaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        logoDimensionesPanel.add(secondRowAparienciaLblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        firstRowConfigPanel.setLayout(new java.awt.GridBagLayout());

        logoSizeLblPanel.setLayout(new java.awt.GridBagLayout());

        firstRowNombreArchivoLogoPosXLbl.setText("Posición X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoPosXLbl, gridBagConstraints);

        firstRowNombreArchivoLogoPosYLbl.setText("Posición Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoPosYLbl, gridBagConstraints);

        firstRowNombreArchivoLogoAnchoLbl.setText("Ancho");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoAnchoLbl, gridBagConstraints);

        firstRowNombreArchivoLogoAlturaLbl.setText("Altura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoAlturaLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        firstRowConfigPanel.add(logoSizeLblPanel, gridBagConstraints);

        logoSizeSpinnerPanel.setLayout(new java.awt.GridBagLayout());

        logoPosXSpinner.setMinimumSize(new java.awt.Dimension(150, 22));
        logoPosXSpinner.setName("factura.logo.x"); // NOI18N
        logoPosXSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoPosXSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoPosXSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        logoSizeSpinnerPanel.add(logoPosXSpinner, gridBagConstraints);

        logoPosYSpinner.setName("factura.logo.y"); // NOI18N
        logoPosYSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoPosYSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoPosYSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        logoSizeSpinnerPanel.add(logoPosYSpinner, gridBagConstraints);

        logoAnchoSpinner.setName("factura.logo.width"); // NOI18N
        logoAnchoSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoAnchoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoAnchoSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        logoSizeSpinnerPanel.add(logoAnchoSpinner, gridBagConstraints);

        logoAlturaSpinner.setName("factura.logo.height"); // NOI18N
        logoAlturaSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoAlturaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoAlturaSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        logoSizeSpinnerPanel.add(logoAlturaSpinner, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        firstRowConfigPanel.add(logoSizeSpinnerPanel, gridBagConstraints);

        logoDimensionesPanel.add(firstRowConfigPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, -4, 270, 110));

        facturacionLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        facturacionLbl.setText("FACTURACIÓN");

        precioUnitarioNumDecimalesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rowCantidadesPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarSiempreDecimalesLabel1.setText("Posiciones decimales en el precio por unidad");
        mostrarSiempreDecimalesLabel1.setPreferredSize(new java.awt.Dimension(200, 16));
        rowCantidadesPanel1.add(mostrarSiempreDecimalesLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 25));

        decimalesPrecioJSpinner.setMinimumSize(new java.awt.Dimension(150, 22));
        decimalesPrecioJSpinner.setName("factura.numdecimales_precio"); // NOI18N
        decimalesPrecioJSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        decimalesPrecioJSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                decimalesPrecioJSpinnerStateChanged(evt);
            }
        });
        rowCantidadesPanel1.add(decimalesPrecioJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, 25));

        questionMarkImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/question_mark.png"))); // NOI18N
        questionMarkImgLbl.setToolTipText("<html>\nIndependientemente de la cifra escogida, los cálculos se realizarán con <b>todos</b> los decimales.<br>\nAquí solo se elige lo que se visualizará en la factura.\n</html>");
        questionMarkImgLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rowCantidadesPanel1.add(questionMarkImgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        precioUnitarioNumDecimalesPanel.add(rowCantidadesPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 25));

        cantidadDecimalesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rowCantidadesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarSiempreDecimalesLabel.setText("Mostrar siempre decimales en las cantidades");
        rowCantidadesPanel.add(mostrarSiempreDecimalesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 35));

        mostrarSiempreDecimalesCheckBox.setName("factura.forzar_decimales_cantidad"); // NOI18N
        mostrarSiempreDecimalesCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mostrarSiempreDecimalesCheckBoxStateChanged(evt);
            }
        });
        rowCantidadesPanel.add(mostrarSiempreDecimalesCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 20, 35));

        cantidadDecimalesPanel.add(rowCantidadesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadDecimalesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(logoDimensionesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPathPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoLbl)
                            .addComponent(facturacionLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(precioUnitarioNumDecimalesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoPathPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoDimensionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facturacionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadDecimalesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioUnitarioNumDecimalesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstRowExaminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstRowExaminarBtnActionPerformed
        controller.openFileChooser((JButton)evt.getSource());
    }//GEN-LAST:event_firstRowExaminarBtnActionPerformed

    private void logoPosXSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoPosXSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoPosXSpinnerStateChanged

    private void logoPosYSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoPosYSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoPosYSpinnerStateChanged

    private void logoAnchoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoAnchoSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoAnchoSpinnerStateChanged

    private void logoAlturaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoAlturaSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoAlturaSpinnerStateChanged

    private void mostrarSiempreDecimalesCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mostrarSiempreDecimalesCheckBoxStateChanged
        controller.setDecimalConfig((JCheckBox)evt.getSource());
    }//GEN-LAST:event_mostrarSiempreDecimalesCheckBoxStateChanged

    private void decimalesPrecioJSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_decimalesPrecioJSpinnerStateChanged
        controller.setNewDecimalesPrecio((JSpinner)evt.getSource());
    }//GEN-LAST:event_decimalesPrecioJSpinnerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cantidadDecimalesPanel;
    public javax.swing.JSpinner decimalesPrecioJSpinner;
    private javax.swing.JLabel facturacionLbl;
    private javax.swing.JPanel firstRowAparienciaConfigPanel;
    private javax.swing.JLabel firstRowAparienciaLbl;
    private javax.swing.JPanel firstRowAparienciaLblPanel;
    private javax.swing.JPanel firstRowConfigPanel;
    public javax.swing.JButton firstRowExaminarBtn;
    public javax.swing.JLabel firstRowNombreArchivoLogoAlturaLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoAnchoLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoPosXLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoPosYLbl;
    public javax.swing.JSpinner logoAlturaSpinner;
    public javax.swing.JSpinner logoAnchoSpinner;
    private javax.swing.JPanel logoDimensionesPanel;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel logoPathPanel;
    public javax.swing.JSpinner logoPosXSpinner;
    public javax.swing.JSpinner logoPosYSpinner;
    private javax.swing.JPanel logoSizeLblPanel;
    private javax.swing.JPanel logoSizeSpinnerPanel;
    public javax.swing.JCheckBox mostrarSiempreDecimalesCheckBox;
    private javax.swing.JLabel mostrarSiempreDecimalesLabel;
    private javax.swing.JLabel mostrarSiempreDecimalesLabel1;
    private javax.swing.JPanel precioUnitarioNumDecimalesPanel;
    private javax.swing.JLabel questionMarkImgLbl;
    private javax.swing.JPanel rowCantidadesPanel;
    private javax.swing.JPanel rowCantidadesPanel1;
    private javax.swing.JLabel secondRowAparienciaLbl;
    private javax.swing.JPanel secondRowAparienciaLblPanel;
    // End of variables declaration//GEN-END:variables
}
