
package jud.gestorfacturas.gui.configuracion;

import javax.swing.JButton;
import javax.swing.JSpinner;

public class ConfigFacturaView extends javax.swing.JPanel {

    ConfigFacturaController controller;
    
    public ConfigFacturaView(ConfigFacturaController _controller) {
        this.controller = _controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        firstRowAparienciaLblPanel = new javax.swing.JPanel();
        firstRowAparienciaLbl = new javax.swing.JLabel();
        firstRowAparienciaConfigPanel = new javax.swing.JPanel();
        firstRowExaminarBtn = new javax.swing.JButton();
        firstRowNombreArchivoLogoLbl = new javax.swing.JLabel();
        secondRowAparienciaPanel = new javax.swing.JPanel();
        secondRowAparienciaLblPanel = new javax.swing.JPanel();
        secondRowAparienciaLbl = new javax.swing.JLabel();
        firstRowConfigPanel = new javax.swing.JPanel();
        logoSizeLblPanel = new javax.swing.JPanel();
        firstRowNombreArchivoLogoPosXLbl = new javax.swing.JLabel();
        firstRowNombreArchivoLogoPosYLbl = new javax.swing.JLabel();
        firstRowNombreArchivoLogoAnchoLbl = new javax.swing.JLabel();
        firstRowNombreArchivoLogoAlturaLbl = new javax.swing.JLabel();
        logoSizeSpinnerPanel = new javax.swing.JPanel();
        logoPosXSpinner = new javax.swing.JSpinner();
        logoPosYSpinner = new javax.swing.JSpinner();
        logoAnchoSpinner = new javax.swing.JSpinner();
        logoAlturaSpinner = new javax.swing.JSpinner();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstRowAparienciaLblPanel.setLayout(new java.awt.BorderLayout());

        firstRowAparienciaLbl.setText("Logo utilizado en facturas");
        firstRowAparienciaLblPanel.add(firstRowAparienciaLbl, java.awt.BorderLayout.CENTER);

        jPanel1.add(firstRowAparienciaLblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 35));

        firstRowAparienciaConfigPanel.setLayout(new java.awt.GridBagLayout());

        firstRowExaminarBtn.setText("Examinar...");
        firstRowExaminarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        firstRowExaminarBtn.setName("factura.logo.path"); // NOI18N
        firstRowExaminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstRowExaminarBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        firstRowAparienciaConfigPanel.add(firstRowExaminarBtn, gridBagConstraints);

        firstRowNombreArchivoLogoLbl.setText("nombreArchivo.ext");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        firstRowAparienciaConfigPanel.add(firstRowNombreArchivoLogoLbl, gridBagConstraints);

        jPanel1.add(firstRowAparienciaConfigPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, -4, 250, 40));

        secondRowAparienciaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondRowAparienciaLblPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondRowAparienciaLbl.setText("Dimensiones del logo en la factura");
        secondRowAparienciaLblPanel.add(secondRowAparienciaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        secondRowAparienciaPanel.add(secondRowAparienciaLblPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        firstRowConfigPanel.setLayout(new java.awt.GridBagLayout());

        logoSizeLblPanel.setLayout(new java.awt.GridBagLayout());

        firstRowNombreArchivoLogoPosXLbl.setText("Posición X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoPosXLbl, gridBagConstraints);

        firstRowNombreArchivoLogoPosYLbl.setText("Posición Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoPosYLbl, gridBagConstraints);

        firstRowNombreArchivoLogoAnchoLbl.setText("Ancho");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoAnchoLbl, gridBagConstraints);

        firstRowNombreArchivoLogoAlturaLbl.setText("Altura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        logoSizeLblPanel.add(firstRowNombreArchivoLogoAlturaLbl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        firstRowConfigPanel.add(logoSizeLblPanel, gridBagConstraints);

        logoSizeSpinnerPanel.setLayout(new java.awt.GridBagLayout());

        logoPosXSpinner.setMinimumSize(new java.awt.Dimension(150, 22));
        logoPosXSpinner.setName("factura.logo.x"); // NOI18N
        logoPosXSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoPosXSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoPosXSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        logoSizeSpinnerPanel.add(logoPosXSpinner, gridBagConstraints);

        logoPosYSpinner.setName("factura.logo.y"); // NOI18N
        logoPosYSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoPosYSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoPosYSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        logoSizeSpinnerPanel.add(logoPosYSpinner, gridBagConstraints);

        logoAnchoSpinner.setName("factura.logo.width"); // NOI18N
        logoAnchoSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoAnchoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoAnchoSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        logoSizeSpinnerPanel.add(logoAnchoSpinner, gridBagConstraints);

        logoAlturaSpinner.setName("factura.logo.height"); // NOI18N
        logoAlturaSpinner.setPreferredSize(new java.awt.Dimension(100, 22));
        logoAlturaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                logoAlturaSpinnerStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        logoSizeSpinnerPanel.add(logoAlturaSpinner, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        firstRowConfigPanel.add(logoSizeSpinnerPanel, gridBagConstraints);

        secondRowAparienciaPanel.add(firstRowConfigPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, -4, 270, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(secondRowAparienciaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondRowAparienciaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstRowExaminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstRowExaminarBtnActionPerformed
        controller.openFileChooser((JButton)evt.getSource());
    }//GEN-LAST:event_firstRowExaminarBtnActionPerformed

    private void logoPosXSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoPosXSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoPosXSpinnerStateChanged

    private void logoPosYSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoPosYSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoPosYSpinnerStateChanged

    private void logoAnchoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoAnchoSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoAnchoSpinnerStateChanged

    private void logoAlturaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_logoAlturaSpinnerStateChanged
        controller.setNewLogoProperty((JSpinner)evt.getSource());
    }//GEN-LAST:event_logoAlturaSpinnerStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel firstRowAparienciaConfigPanel;
    private javax.swing.JLabel firstRowAparienciaLbl;
    private javax.swing.JPanel firstRowAparienciaLblPanel;
    private javax.swing.JPanel firstRowConfigPanel;
    public javax.swing.JButton firstRowExaminarBtn;
    public javax.swing.JLabel firstRowNombreArchivoLogoAlturaLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoAnchoLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoPosXLbl;
    public javax.swing.JLabel firstRowNombreArchivoLogoPosYLbl;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JSpinner logoAlturaSpinner;
    public javax.swing.JSpinner logoAnchoSpinner;
    public javax.swing.JSpinner logoPosXSpinner;
    public javax.swing.JSpinner logoPosYSpinner;
    private javax.swing.JPanel logoSizeLblPanel;
    private javax.swing.JPanel logoSizeSpinnerPanel;
    private javax.swing.JLabel secondRowAparienciaLbl;
    private javax.swing.JPanel secondRowAparienciaLblPanel;
    private javax.swing.JPanel secondRowAparienciaPanel;
    // End of variables declaration//GEN-END:variables
}
