
package jud.gestorfacturas.gui.configuracion;

import java.util.ArrayList;
import java.util.List;
import utils.ConfigUtils;

public class ConfigAparienciaView extends javax.swing.JPanel {

    ConfigAparienciaController controller;
    String[] aparienciaUIModel;
    
    public ConfigAparienciaView(ConfigAparienciaController _controller) {
        this.controller = _controller;
        // Set themes JComboBox
        List<String> aparienciaUIModelList = new ArrayList<String>();
        for (String str : ConfigUtils.UI_THEMES.keySet()) {
            aparienciaUIModelList.add(str);
        }
        aparienciaUIModel = new String[aparienciaUIModelList.size()];
        aparienciaUIModel = aparienciaUIModelList.toArray(aparienciaUIModel);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstRowPanel = new javax.swing.JPanel();
        firstRowLabelPanel = new javax.swing.JPanel();
        firstRowAparienciaLbl = new javax.swing.JLabel();
        firstRowOptionPanel = new javax.swing.JPanel();
        firstRowAparienciaComboBox = new javax.swing.JComboBox<>();

        firstRowPanel.setLayout(new java.awt.GridLayout(1, 2));

        firstRowLabelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        firstRowAparienciaLbl.setText("Apariencia IU");
        firstRowLabelPanel.add(firstRowAparienciaLbl);

        firstRowPanel.add(firstRowLabelPanel);

        firstRowOptionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        firstRowAparienciaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(aparienciaUIModel));
        firstRowAparienciaComboBox.setName("ui.theme"); // NOI18N
        firstRowAparienciaComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                firstRowAparienciaComboBoxItemStateChanged(evt);
            }
        });
        firstRowOptionPanel.add(firstRowAparienciaComboBox);

        firstRowPanel.add(firstRowOptionPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(firstRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstRowAparienciaComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstRowAparienciaComboBoxItemStateChanged
        controller.aparienciaUIChanged(evt);
    }//GEN-LAST:event_firstRowAparienciaComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> firstRowAparienciaComboBox;
    private javax.swing.JLabel firstRowAparienciaLbl;
    private javax.swing.JPanel firstRowLabelPanel;
    private javax.swing.JPanel firstRowOptionPanel;
    private javax.swing.JPanel firstRowPanel;
    // End of variables declaration//GEN-END:variables
}
