
package jud.gestorfacturas.gui.configuracion;

import javax.swing.DefaultListModel;

public class ImportarView extends javax.swing.JPanel {

    ImportarController controller;
    DefaultListModel<String> importacionesPendientesModel = new DefaultListModel<>();
    
    public ImportarView(ImportarController _controller) {
        this.controller = _controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        firstRowPanel = new javax.swing.JPanel();
        firstRowLabelPanel = new javax.swing.JPanel();
        firstRowImportarFacturasLbl = new javax.swing.JLabel();
        firstRowOptionPanel = new javax.swing.JPanel();
        firstRowExaminarBtn = new javax.swing.JButton();
        firstRowResultPanel = new javax.swing.JPanel();
        firstRowResultLbl = new javax.swing.JLabel();
        secondRowPanel = new javax.swing.JPanel();
        secondRowLabelPanel = new javax.swing.JPanel();
        firstRowImportarFacturasLbl1 = new javax.swing.JLabel();
        secondRowOptionPanel = new javax.swing.JPanel();
        secondRowExaminarBtn = new javax.swing.JButton();
        secondRowResultPanel = new javax.swing.JPanel();
        secondRowResultLbl = new javax.swing.JLabel();
        thirdRowPanel = new javax.swing.JPanel();
        thirdRowLabelPanel = new javax.swing.JPanel();
        thirdRowImportarFacturasLbl = new javax.swing.JLabel();
        thirdRowOptionPanel = new javax.swing.JPanel();
        thirdRowExaminarBtn = new javax.swing.JButton();
        thirdRowResultPanel = new javax.swing.JPanel();
        thirdRowResultLbl = new javax.swing.JLabel();
        fourthRowPanel = new javax.swing.JPanel();
        fourthRowLabelPanel = new javax.swing.JPanel();
        fourthRowImportarFacturasLbl = new javax.swing.JLabel();
        fourthRowOptionPanel = new javax.swing.JPanel();
        fourthRowExaminarBtn = new javax.swing.JButton();
        fourthRowResultPanel = new javax.swing.JPanel();
        fourthRowResultLbl = new javax.swing.JLabel();
        finalRowImportadoPanel = new javax.swing.JPanel();
        ejecutarImporteBtn = new javax.swing.JButton();
        listPanel = new javax.swing.JPanel();
        listLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        importacionesList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 367));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        firstRowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstRowLabelPanel.setMinimumSize(new java.awt.Dimension(280, 26));
        firstRowLabelPanel.setPreferredSize(new java.awt.Dimension(280, 26));
        firstRowLabelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        firstRowImportarFacturasLbl.setText("Importar base de datos de emisor (datos pers.)");
        firstRowLabelPanel.add(firstRowImportarFacturasLbl);

        firstRowPanel.add(firstRowLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 33));

        firstRowExaminarBtn.setText("Examinar...");
        firstRowExaminarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        firstRowExaminarBtn.setName("BDEmisor"); // NOI18N
        firstRowExaminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstRowExaminarBtnActionPerformed(evt);
            }
        });
        firstRowOptionPanel.add(firstRowExaminarBtn);

        firstRowPanel.add(firstRowOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, -1));

        firstRowResultPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        firstRowResultLbl.setText("*Un único archivo tipo JSON.");
        firstRowResultLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        firstRowResultPanel.add(firstRowResultLbl);

        firstRowPanel.add(firstRowResultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 250, 33));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(firstRowPanel, gridBagConstraints);

        secondRowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondRowLabelPanel.setMinimumSize(new java.awt.Dimension(280, 26));
        secondRowLabelPanel.setPreferredSize(new java.awt.Dimension(280, 26));
        secondRowLabelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        firstRowImportarFacturasLbl1.setText("Importar base de datos de clientes");
        secondRowLabelPanel.add(firstRowImportarFacturasLbl1);

        secondRowPanel.add(secondRowLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 33));

        secondRowExaminarBtn.setText("Examinar...");
        secondRowExaminarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        secondRowExaminarBtn.setName("BDClientes"); // NOI18N
        secondRowExaminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondRowExaminarBtnActionPerformed(evt);
            }
        });
        secondRowOptionPanel.add(secondRowExaminarBtn);

        secondRowPanel.add(secondRowOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, -1));

        secondRowResultPanel.setMinimumSize(new java.awt.Dimension(71, 26));
        secondRowResultPanel.setPreferredSize(new java.awt.Dimension(71, 26));
        secondRowResultPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        secondRowResultLbl.setText("*Archivos tipo JSON.");
        secondRowResultLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        secondRowResultPanel.add(secondRowResultLbl);

        secondRowPanel.add(secondRowResultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 250, 33));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(secondRowPanel, gridBagConstraints);

        thirdRowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thirdRowLabelPanel.setMinimumSize(new java.awt.Dimension(280, 26));
        thirdRowLabelPanel.setPreferredSize(new java.awt.Dimension(280, 26));
        thirdRowLabelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        thirdRowImportarFacturasLbl.setText("Importar base de datos de facturas");
        thirdRowLabelPanel.add(thirdRowImportarFacturasLbl);

        thirdRowPanel.add(thirdRowLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 33));

        thirdRowExaminarBtn.setText("Examinar...");
        thirdRowExaminarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        thirdRowExaminarBtn.setName("BDFacturas"); // NOI18N
        thirdRowExaminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdRowExaminarBtnActionPerformed(evt);
            }
        });
        thirdRowOptionPanel.add(thirdRowExaminarBtn);

        thirdRowPanel.add(thirdRowOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, -1));

        thirdRowResultPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        thirdRowResultLbl.setText("*Archivos tipo JSON.");
        thirdRowResultPanel.add(thirdRowResultLbl);

        thirdRowPanel.add(thirdRowResultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 250, 33));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(thirdRowPanel, gridBagConstraints);

        fourthRowPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fourthRowLabelPanel.setMinimumSize(new java.awt.Dimension(280, 26));
        fourthRowLabelPanel.setPreferredSize(new java.awt.Dimension(280, 26));
        fourthRowLabelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fourthRowImportarFacturasLbl.setText("Importar PDF facturas");
        fourthRowLabelPanel.add(fourthRowImportarFacturasLbl);

        fourthRowPanel.add(fourthRowLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 33));

        fourthRowExaminarBtn.setText("Examinar...");
        fourthRowExaminarBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        fourthRowExaminarBtn.setName("PDFFacturas"); // NOI18N
        fourthRowExaminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthRowExaminarBtnActionPerformed(evt);
            }
        });
        fourthRowOptionPanel.add(fourthRowExaminarBtn);

        fourthRowPanel.add(fourthRowOptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, -1));

        fourthRowResultPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fourthRowResultLbl.setText("*Archivos tipo PDF.");
        fourthRowResultPanel.add(fourthRowResultLbl);

        fourthRowPanel.add(fourthRowResultPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 250, 33));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(fourthRowPanel, gridBagConstraints);

        finalRowImportadoPanel.setMinimumSize(new java.awt.Dimension(650, 35));
        finalRowImportadoPanel.setPreferredSize(new java.awt.Dimension(650, 35));
        finalRowImportadoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ejecutarImporteBtn.setText("Ejecutar importación");
        ejecutarImporteBtn.setPreferredSize(new java.awt.Dimension(250, 250));
        ejecutarImporteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarImporteBtnActionPerformed(evt);
            }
        });
        finalRowImportadoPanel.add(ejecutarImporteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 170, 25));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(finalRowImportadoPanel, gridBagConstraints);

        listPanel.setMinimumSize(new java.awt.Dimension(750, 200));
        listPanel.setPreferredSize(new java.awt.Dimension(750, 200));
        listPanel.setLayout(new java.awt.BorderLayout(0, 5));

        listLabel.setText("Los siguientes archivos están preparados para ser importados. Haga doble click para eliminarlos de la cola.");
        listLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        listPanel.add(listLabel, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(620, 200));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(620, 200));
        jScrollPane1.setRequestFocusEnabled(false);

        importacionesList.setModel(importacionesPendientesModel);
        importacionesList.setMaximumSize(new java.awt.Dimension(600, 150));
        importacionesList.setMinimumSize(new java.awt.Dimension(600, 150));
        importacionesList.setName(""); // NOI18N
        importacionesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importacionesListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(importacionesList);

        listPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(listPanel, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("*Cualquier conflicto entre \"ID\" y \"números de factura\" dentro de una base de datos se resolverá dando preferencia a los objetos que antes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText(" se registren, el resto serán descartados. El orden en el que se procesará cada archivo se muestra en el listado superior.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void firstRowExaminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstRowExaminarBtnActionPerformed
        controller.importFile(firstRowExaminarBtn, firstRowResultLbl, false);
    }//GEN-LAST:event_firstRowExaminarBtnActionPerformed

    private void secondRowExaminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondRowExaminarBtnActionPerformed
        controller.importFile(secondRowExaminarBtn, secondRowResultLbl, true);
    }//GEN-LAST:event_secondRowExaminarBtnActionPerformed

    private void thirdRowExaminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdRowExaminarBtnActionPerformed
        controller.importFile(thirdRowExaminarBtn, thirdRowResultLbl, true);
    }//GEN-LAST:event_thirdRowExaminarBtnActionPerformed

    private void fourthRowExaminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthRowExaminarBtnActionPerformed
        controller.importFile(fourthRowExaminarBtn, fourthRowResultLbl, true);
    }//GEN-LAST:event_fourthRowExaminarBtnActionPerformed

    private void importacionesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importacionesListMouseClicked
        if (evt.getClickCount() >= 2) { // double-click
            controller.removeImportFile(evt);
        }
    }//GEN-LAST:event_importacionesListMouseClicked

    private void ejecutarImporteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarImporteBtnActionPerformed
        controller.ejecutarImportacionGlobal();
    }//GEN-LAST:event_ejecutarImporteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ejecutarImporteBtn;
    private javax.swing.JPanel finalRowImportadoPanel;
    public javax.swing.JButton firstRowExaminarBtn;
    private javax.swing.JLabel firstRowImportarFacturasLbl;
    private javax.swing.JLabel firstRowImportarFacturasLbl1;
    private javax.swing.JPanel firstRowLabelPanel;
    private javax.swing.JPanel firstRowOptionPanel;
    private javax.swing.JPanel firstRowPanel;
    public javax.swing.JLabel firstRowResultLbl;
    private javax.swing.JPanel firstRowResultPanel;
    public javax.swing.JButton fourthRowExaminarBtn;
    private javax.swing.JLabel fourthRowImportarFacturasLbl;
    private javax.swing.JPanel fourthRowLabelPanel;
    private javax.swing.JPanel fourthRowOptionPanel;
    private javax.swing.JPanel fourthRowPanel;
    public javax.swing.JLabel fourthRowResultLbl;
    private javax.swing.JPanel fourthRowResultPanel;
    public javax.swing.JList<String> importacionesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listLabel;
    private javax.swing.JPanel listPanel;
    public javax.swing.JButton secondRowExaminarBtn;
    private javax.swing.JPanel secondRowLabelPanel;
    private javax.swing.JPanel secondRowOptionPanel;
    private javax.swing.JPanel secondRowPanel;
    public javax.swing.JLabel secondRowResultLbl;
    private javax.swing.JPanel secondRowResultPanel;
    public javax.swing.JButton thirdRowExaminarBtn;
    private javax.swing.JLabel thirdRowImportarFacturasLbl;
    private javax.swing.JPanel thirdRowLabelPanel;
    private javax.swing.JPanel thirdRowOptionPanel;
    private javax.swing.JPanel thirdRowPanel;
    public javax.swing.JLabel thirdRowResultLbl;
    private javax.swing.JPanel thirdRowResultPanel;
    // End of variables declaration//GEN-END:variables
}
